#!/bin/bash

./gradlew shadowJar \
  && cp build/libs/mirror-all.jar ~/ \
  && scp build/libs/mirror-all.jar ld1:~/ \
  && scp build/libs/mirror-all.jar sh10:~/ \
  && scp build/libs/mirror-all.jar joist.ws:/var/www/joist.repo/

version=$(git describe --tags --dirty)
echo $version > .version
scp .version joist.ws:/var/www/joist.repo/mirror-version
rm .version

scp mirror joist.ws:/var/www/joist.repo/mirror

